####

POST http://localhost:3030/enquete
Content-Type: application/json

{   
    "titulo":"Está sendo divertido fazer esse trabalho?",
    "dataInicio":"2022-01-20T17:20:00.000Z",
    "dataFim":"2022-10-20T17:20:00.000Z"
}

####

GET http://localhost:3030/enquete/2

####

GET http://localhost:3030/enquete/

####

PUT http://localhost:3030/enquete
Content-Type: application/json

{   
    "idEnquete":4,
    "titulo":"Update!",
    "dataInicio":"2020-01-20T17:20:00.000Z",
    "dataFim":"2020-01-30T17:20:00.000Z"
}


##########
DELETE http://localhost:3030/enquete
Content-Type: application/json

{   
    "idEnquete":1
}

###############

GET http://localhost:3030/enquete/count

####
##Fim testes Enquete
###

POST http://localhost:3030/option
Content-Type: application/json

{   
    "idEnquete":2,
    "description":"Eita!"
}

####

GET http://localhost:3030/option/

###############

GET http://localhost:3030/option/count

####



GET http://localhost:3030/option/count/2

###############

GET http://localhost:3030/option/2

####

GET http://localhost:3030/option/enq/2

####

PUT http://localhost:3030/option
Content-Type: application/json

{   
    "idOption":2,
    "description":"Eita!!"
}

#######

DELETE http://localhost:3030/option
Content-Type: application/json

{   
    "idOption":3
}

#########
###Fim Option
####

POST http://localhost:3030/voto
Content-Type: application/json

{   
    "idEnquete":2,
    "idOption":5
}


###############
GET http://localhost:3030/voto

###############
GET http://localhost:3030/voto/5

###############
GET http://localhost:3030/voto/enq/2


###############
GET http://localhost:3030/voto/opt/5


################


GET http://localhost:3030/voto/count

###############

GET http://localhost:3030/voto/count/5

####

GET http://localhost:3030/voto/count/enq/2

####






PUT http://localhost:3030/voto
Content-Type: application/json

{   
    "idVoto":4,
    "idEnquete":3,
    "idOption":5
}

#######

DELETE http://localhost:3030/voto
Content-Type: application/json

{   
    "idVoto":5
}